apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp
  namespace: nodeapps-namespace
  labels:
    app: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejsapp
        image: mysimpleapprepo.azurecr.io/nodejsapp:appversion
        ports:
        - containerPort: 80
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodejsapp
  namespace: nodeapps-namespace
spec:
  selector:
    app: nodejs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  externalTrafficPolicy: Local
  type: LoadBalancer

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-http-backend
  namespace: nodeapps-namespace
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: nodejsapp
            port:
              number: 80
        pathType: Exact
